### ISSUE TITLE
allow --verbose in git commit

### ISSUE THREAD

**Issue by Guria** [commitizen/cz-cli#103]

**Comment by jimthedev** [comment]
Hi there. Originally we allowed this but then we realized that it was very difficult to support this and multi line commit messages. With that said, we could look into a second command `git czo` or something like that allows you to pass options. Can you provide me with a few commands that currently don't work for you so that I can write some test cases? Thanks.

**Comment by kamushin** [comment]
`git cz --verbose`
will return 
`{ [Error: Command failed: /bin/sh -c git commit -m "*******"  -verbose
error: did you mean `--verbose` (with two dashes ?)
]
  killed: false,
  code: 129,
  signal: null,
  cmd: '/bin/sh -c git commit -m "*****"  -verbose ' }
`

**Comment by jimthedev** [comment]
--verbose should be fixed in v2.6.3. This is just a hotfix for verbose. We're going to have to find a longer term options fix like I mentioned before, but I don't have the bandwidth right now to write that feature. Would welcome PRs in this area.
