### ISSUE TITLE
git-cz doesn't return an error code when commit fails or is canceled

### ISSUE THREAD

**Issue by bitjson** [commitizen/cz-cli#162]
This makes it hard for other utilities or scripts to confirm a commit happened. Eg: https://github.com/bitjson/wip/issues/3#issuecomment-199331449

**Comment by jimthedev** [comment]
I agree. This is an issue that needs fixed. It is going to take some cleanup and I won't be able to do it immediately due to being stretched pretty thin, but it should be possible to accomplish and should be relatively high on the priority list in order to be a good cli citizen with regards to exit codes.

**Comment by marionebl** [comment]
This should be fixed via https://github.com/commitizen/cz-cli/pull/256

**Comment by LinusU** [comment]
Please reopen if problem persists
