### ISSUE TITLE
Documentation for running as a local module

### ISSUE THREAD

**Issue by jacopotarantino** [commitizen/cz-cli#165]
I consider this a best practice because you don't have to assume that a user has cz installed globally. I managed to get it running properly on my machine but there's probably a better way to do it. Could you help me document this feature?

**Comment by jimthedev** [comment]
I agree. In general, node projects should install commitizen as a local dev dependency using `npm i -D commitizen` and this should probably be changed in the documentation. For some projects it may be preferable to use a global, but I think that should probably be a secondary option in the docs and not the primary suggestion.

Once you have commitizen installed as a local dev dependency you can execute `./node_modules/.bin/commitizen` or `./node_modules/.bin/git-cz` in order to actually use the commands. 

You would initialize a commitizen adapter using: `./node_modules/.bin/commitizen init cz-conventional-changelog --save-dev --save-exact`

And you can then add some nice npm run scripts in your package.json pointing to the local version of commitizen:

```
...
  "scripts": {
    "commit": "git-cz"
  }
```

This will be more convenient for your users because then if they want to do a commit, all they need to do is run `npm run commit` and they will get the prompts needed to start a commit!

In order to document this process, all you need to do is:

1. Fork this repo
2. Edit README.md on your fork. Commit your changes.
3. Put in a pull request with this repository.

For more information on putting in pull requests, see [Make A Pull Request](http://makeapullrequest.com/).

Hope that helps and look forward to your PR!

**Comment by jacopotarantino** [comment]
Thanks for the help and sorry it took me so long to get back on this! I have a PR open at https://github.com/commitizen/cz-cli/pull/300. Copied a lot of your reply since it was basically exactly what I was looking for haha. Thanks again!
