### ISSUE TITLE
"Longer description" and "List any breaking changes" to support multilines

### ISSUE THREAD

**Issue by tunnckoCore** [commitizen/cz-cli#398]
Or at least one of them.

I'm talking for the CLI interface. And only when two empty new lines, then to finish it. I find it pretty weird if I want to list few things and I am forced to list them in "one line", so i separated my things and thoughts with ";".

**Comment by jimthedev** [comment]
I understand what you're asking for. 

We actually do support this. You can fork the cz-conventional-changelog adapter and change the fields you want to be editor fields instead of input. This would allow you to type multiline input for that fields.  You can read more about inquirer's editor field here: https://github.com/SBoudrias/Inquirer.js/
