### ISSUE TITLE
How to configure commitzen.json

### ISSUE THREAD

**Issue by krishna63** [commitizen/cz-cli#431]
Hi Team,

I have installed commitizen and intialized the conventional log adapter and now i have two requirements, not sure how to acheive it please help me out

I want to make the description also required field then how should do that ?
I want to specify the length of the description to 72 characters ?

Regarding configuration
I have not installed commitizen globally so when ever i want to run the command **commitizen init <adapter name> ** or  **git cz**, i need to go to the ** ./node_modules/.bin** directory and execute the command for the questions to come ?

how can i over come this, i know it is bit silly question but i am bit new to this ?

**Comment by jimthedev** [comment]
Hi @krishna63. Right now if you want to make changes to the adapter config (required fields, length of characters) then you'd need to fork the adapter, publish it to github, then initialize commitizen to point at your fork. We make it hard for you because we don't want to maintain the many many permutations that people want out of their config. We could never manage all of these so if you'd like to manage the config then you will need to take on ownership of the fork of that adapter. For more info on exactly how to do this you can read this: https://github.com/commitizen/cz-cli/issues/62#issuecomment-155103053



To answer your second question about ./node_modules/.bin see http://stackoverflow.com/a/15157360
