### ISSUE TITLE
precommit runs twice when using husky 

### ISSUE THREAD

**Issue by faceyspacey** [commitizen/cz-cli#432]
Here's my relevant `package.json`:
```json
"devDependencies": {
    "commitizen": "^2.9.6",
    "cz-conventional-changelog": "^2.0.0",
    "husky": "^0.13.2",
    "lint-staged": "^3.4.0",
    "prettier": "^1.2.2"
},
"scripts": {
   "precommit": "lint-staged --verbose",
   "commit": "git-cz",
},
"lint-staged": {
    "*.js": [
      "prettier --single-quote --semi=false --write",
      "git add"
    ]
},
"config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
},
```

`lint-staged` is *correctly* called once ***before*** the `commitizen` command line form appears, and then *incorrectly* `husky - npm run -s precommit` is run ***after***. Typically without `commitizen` only `lint-staged` is called. Somehow `commitizen` is triggering `husky` to be called. No where do I have this script: `npm run -s precommit`. It seems `commitizen` somehow triggers it after you complete the form.

**Comment by jimthedev** [comment]
Can you post what your workflow looks like without commitizen in the mix
including when and how you run git add and git commit in this configuration?

-- 
Jim ForCy

**Comment by faceyspacey** [comment]
I simply call `git add`, and `git commit`. The `precommit` script thanks to husky will run `lint-staged`. So you will see `husky - npm run -s precommit` run in the terminal. 

Whereas if you run `npm run commit` for the first commit log you see:

```
> redux-first-router@0.0.0-development precommit /Users/jamesgillmore/React/pure-redux-router
> lint-staged --verbose && npm test
```

Basically it seems 2 different versions of `precommit` are being run when commitizen is used, as they are logged with different messages.

**Comment by faceyspacey** [comment]
Here's a package you can clone and immediately see it in action:

https://github.com/faceyspacey/redux-first-router

**Comment by jimthedev** [comment]
That is a [bug in husky](https://github.com/typicode/husky/issues/99) that happens due to a "feature" of npm-scripts that auto run scripts with the name prexxx where xxx is the name of another script. So, because you're using `commit` and `precommit` it is running them twice. 

Until husky fixes this you can simply change your commitizen task to `cmt` or something else (`cz`, `co`, etc).

We could probably update our docs to reflect that when using commitizen and husky you should pick another name than `npm run commit`. Want to put in a PR?

**Comment by faceyspacey** [comment]
nice find!

Here's the PR as requested: https://github.com/commitizen/cz-cli/pull/433
