### ISSUE TITLE
Jira smart commits?

### ISSUE THREAD

**Issue by kentcdodds** [commitizen/cz-cli#6]
This is super awesome. Would it be possible to add custom prompts or something so I could use this to help me with [Jira smart commits](https://confluence.atlassian.com/display/FISHEYE/Using+smart+commits). Basically I'd like to have prompts that ask for:

- Jira Issue Key (this sort of exists currently, though I think the issue key needs to appear first in the message)
- Time spent
- Workflow command (testing, closed, etc.)
- Comment (this could just use what's existing currently, but use the proper command)

This would be super awesome if we could add this.

**Comment by kentcdodds** [comment]
No way! @jimthedev, this is yours? Sweet! :+1:

**Comment by jimthedev** [comment]
:wave: Hi @kentcdodds! Yes it is :) Glad you're enjoying it.

I think this should totally be possible. I use Bitbucket at work with Jira so it would actually be nice to have.

Here's how we'd do it.

1. We'd fork the conventional [changelog adapter](https://github.com/commitizen/cz-conventional-changelog) and call the new repo something like cz-jira-smart-commit.

2. We'd edit package.json and [index.js](https://github.com/commitizen/cz-conventional-changelog/blob/master/index.js) in our newly forked adapter repo to ask for any fields that we want to prompt the user for. We'd also edit the formatting of the final message that gets used for the commit message. It is at the end of index.js.

3. We'd publish it as an npm module.

4. Any user wanting to use this adapter would just edit their .cz.json in the root of the project to point to that adapter and add the adapter to their package.json file.

I probably won't be able to get to it for a week or two but if you want to play with it then let me know and I can set you up in the organization so that you can add adapter repos.

Jim

**Comment by kentcdodds** [comment]
Wow, this is remarkably pluggable/simple. I'll take a stab at it!

**Comment by kentcdodds** [comment]
Could you at least create the initial repo and add me as a team member?

**Comment by jimthedev** [comment]
@kentcdodds You're an admin, now. ;) Name it whatever you like. I need to write some tests and figure out if there is a better way to deal with whitespace formatting in Inquirer prompts, but otherwise it works pretty well for now. Glad you're using it and hacking on it.

**Comment by kentcdodds** [comment]
I'll give it a go!

**Comment by kentcdodds** [comment]
Well, I'm pretty sure we're all set! https://github.com/commitizen/cz-jira-smart-commit

**Comment by jimthedev** [comment]
Great! Psyched to give this a go. Thanks for the repo @kentcdodds!
