### ISSUE TITLE
npm audit issue

### ISSUE THREAD

**Issue by vtereshyn** [commitizen/cz-cli#609]
After running `npm audit` script got an issue with `braces` package which is dependency of `commitizen`.

<img width="555" alt="cz" src="https://user-images.githubusercontent.com/32247411/52943403-bad19b80-3375-11e9-9d5d-4c4675c9a84d.png">

`commitizen` version is 3.0.5

"commitizen": "^3.0.5"

**Comment by celicoo** [comment]
[2]

**Comment by viane** [comment]
+1

**Comment by seantrane** [comment]
This originates through the [`find-node-modules`](https://github.com/callumacrae/find-node-modules) dependency, and its dependency on [`findup-sync`](https://github.com/gulpjs/findup-sync) (`v0.4.2`), and its dependency on [`micromatch`](https://github.com/micromatch/micromatch).

Both `findup-sync` and `micromatch` been patched, and the fix is available in `findup-sync > 1.0.0`. But that fix is almost 2 years old. It does not look like `find-node-modules` is being maintained anymore.

I'm reticent to work on a PR for this without knowing which way maintainers want to go with this; refactor and remove dependency, or influence an update of `find-node-modules`.

**Comment by jimthedev** [comment]
Let's try to update find-node-modules. I hit up find-node-modules author on twitter to see if we can get a merge of the outstanding pr. We'll see if he replies and if so then we can do a PR for findup-sync too. Worst case we fork it and rely on the fork for a bit.

**Comment by jimthedev** [comment]
Ok this looks good he is open to a pr @seantrane  https://twitter.com/callumacrae/status/1098256784287035393

**Comment by afrokick** [comment]
@seantrane  https://github.com/callumacrae/find-node-modules was updated.

**Comment by callumacrae** [comment]
![image](https://user-images.githubusercontent.com/472830/53182263-0c398f00-35f1-11e9-917f-f2b2f244f229.png)

:)

**Comment by jimthedev** [comment]
Merged renovate PR #611

**Comment by jimthedev** [comment]
3.0.6 has the fix from downstream.

**Comment by jimthedev** [comment]
<img width="632" alt="screen shot 2019-02-21 at 12 42 08 pm" src="https://user-images.githubusercontent.com/108938/53193247-2b76f300-35d6-11e9-95fd-9a85f4fbc301.png">

We're good. Thanks all! <3
