### ISSUE TITLE
Set custom scope changes.

### ISSUE THREAD

**Issue by sergey-lapin** [commitizen/cz-cli#62]
Hi, thanks for this awesome project.

I am curious, is it possible to override `Denote the scope of this change ($location, $browser, $compile, etc.):` message?
Would be great to preset scopes for projects.

**Comment by jimthedev** [comment]
Hey @lapanoid Great idea! 

Currently it isn't possible out of the box but it is funny you mention it because @leonardoanalista just published an awesome community adapter called [cz-customizable](https://github.com/leonardoanalista/cz-customizable). I think cz-customizable lets you do things like this. I haven't used it yet but it looks promising. Perhaps we can eventually get @leonardoanalista to merge this functionality into cz-conventional-changelog or maybe he can fashion it in a way that this project could be used by all of the adapters as long as them implement a certain interface. 

Anyhow, if you don't want to use cz-customizable and you're in a pinch then you could use the following steps to create your own adapter:

1. Fork the [cz-conventional-changelog repo](https://github.com/commitizen/cz-conventional-changelog).
2. Change the package.json's name and version field to be cz-my-sweet-adapter and version 1.0.0.
3. Edit index.js to make the wording changes that you desire.
4. Commit your changes and push them up to github.
5. npm publish
6. Direct your users to use cz-my-sweet-adapter instead of cz-conventional-changelog in their repo. 

Now, just to be clear I do hope to offer this kind of functionality in the future but at the moment I've been focusing most of my efforts on the core cli and having a robust test suite. Things are starting to stabilize and the cli backlog is slowly shrinking as we move towards 3.0.0.

Ideally we'd have some way to offer this functionality to more than just the cz-conventional-changelog adapter, but the implementation of essentially extending an adapter seems very specific to the parent adapter. I really would rather adapters be composable instead of extended over and over. 

I am still trying to figure out how we can offer a system of overrides where the needed data and parent dependencies flow down from the cli and events containing captured user data flow back up, while still allowing for robust adapter composition.

In the mean time, check out cz-customizable or try the steps above to fork and create your own adapter. Thanks for the feedback!

**Comment by leonardoanalista** [comment]
I have plans to improve cz-customizable module. 

My plans for `cz-customizable` are:
- set up semantic-releases
- unit tests
- possibly move code to ES6, if to keep consistent with commitizen module or cz-conventional-changelog codebase.
- improve the way the .cz-config.js is read
- add dry run option
- any further customization that could be useful

I am happy to either continue on `cz-customizable` for now or some time later merge this into cz-conventional-changelog. I guess it makes more sense to have 1 repo instead of 2.

Personally, I would like to implement the roadmap above. It is a great chance to apply what I have been reading/watching here: https://egghead.io/series/how-to-write-an-open-source-javascript-library
 
@lapanoid, I have done exactly those steps to fork cz-conventional-changelog. 

We are going to use `cz-customizable` across 5 or 7 teams, some projects are Java and others are AngularJs. Projects have different scopes for sure. That was the motivation behind this module.


Leonardo Correa

**Comment by codeNoobie** [comment]
@jimthedev  Is there any plans to add custom scope feature to commitizen?

**Comment by jimthedev** [comment]
Plans, yes, but no timeline. I’m currently on paternity with our second child. I will accept PRs for this of course.

**Comment by codeNoobie** [comment]
Oh Great! Congratulations!
I will take a look and will submit a PR if I come up with a good solution.

**Comment by codeNoobie** [comment]
@leonardoanalista Do you want to merge your changes to cz-conventional-changelog project as mentioned in your previous message?

**Comment by mesqueeb** [comment]
I also want to set preset scopes! +1

**Comment by cardin** [comment]
> 
> 
> I also want to set preset scopes! +1

I think you can set predefined scopes by following the guide here: https://github.com/streamich/git-cz
