### ISSUE TITLE
1 shelljs vulnerability found

### ISSUE THREAD

**Issue by mysterycommand** [commitizen/cz-cli#635]
I got an alert from GitHub yesterday saying that `shelljs <= 0.8.3` is vulnerable to Command Injection, a dependency (or transitive dependency) of `commitizen` … ah heck, here's a screenshot of the alert:

<img width="756" alt="Screenshot 2019-07-03 13 04 34" src="https://user-images.githubusercontent.com/810398/60611051-5c8cde80-9d93-11e9-92cb-56a0af3f9c35.png">

There's some discussion on shelljs/shelljs#945 that seems to indicate it's "as intended" and up to the `shelljs` consumer to sanitize input. I guess I'm filing this issue to make sure it's on your radar and in hopes that someone more familiar with these kinds of security vulnerabilities can assure me that I have nothing to worry about.

**Comment by edward-hong** [comment]
I received this alert as well

**Comment by jimthedev** [comment]
This has been on my radar but ultimately was getting worked through by both shelljs and execa. As far as I am concerned you're putting in the input into the terminal so we're trusting that input. It is possible that someone installs a vulnerable adapter. There's not much we could do about that since the vulnerability then exists in your code (just remove the dependency). We have no choice but to trust it. It looks like this has been removed recently as an alert https://github.com/shelljs/shelljs/issues/945#issuecomment-512044653

But I don't know if that will cancel existing downstream alerts or not. I am guessing there is a cron that runs this so it'll probably take some time.

**Comment by jimthedev** [comment]
Closing. Github no longer showing vuln.
