### ISSUE TITLE
Throw an error if there are no staged files

### ISSUE THREAD

**Issue by kentcdodds** [commitizen/cz-cli#7]
There's no reason to fill out the prompts if there are no staged files. You can determine this with:

```
git diff --cached
```

:-)

**Comment by jimthedev** [comment]
Great idea. Seems like a no brainier.

**Comment by kentcdodds** [comment]
What needs to happen for this to be implemented? This catches me up pretty much every single time and I also have githooks that take my commits about 15 seconds to go through so I don't realize my mistake until after that's done :-( This would be really helpful.

**Comment by jimthedev** [comment]
Up until now, I've created any of the features I needed in [gulp-git](https://github.com/stevelacy/gulp-git). It is a project that is built for gulp, but we use it specifically for the library modules. I'd love to see Steve break that out into an actual library but it suits our needs but that's a separate conversation. 

Currently it does not have a git diff module. Initially we'd need to create a module for that command and get it merged into Steve's project. He is very responsive and requires tests for all changes. 

Alternatively, we could consider switching the git library that we use. I know this one exists:
https://github.com/steveukx/git-js

It has a diff module that we could try to use for this feature. If it works well then we could migrate the other git commands we use. Bottom line, we either need to add a dependency or get some changes merged into gulp-git and then implement them here.

**Comment by sebastienbarre** [comment]
OK, my gut feeling is that `gulp-git` is the more stable/popular of the two. I inquired in stevelacy/gulp-git#97.

**Comment by jimthedev** [comment]
Thanks!!! I've also started just writing my own wrappers and parsers for v2
so that might be an option for diff. It should pretty much be a regex

**Comment by sebastienbarre** [comment]
Hold on, can't this problem be solved already with `gulp-git`?
* use [`git.status`](https://github.com/stevelacy/gulp-git#gitstatusopt-cb), then just grep to see if "Changes to be committed" is not there,
* or use [`git.exec`](https://github.com/stevelacy/gulp-git#gitexecopt-cb), and execute `diff --cached` from there? (aka `git.exec({args : 'diff --cached'}, function (err, stdout) { ... });`)

**Comment by jimthedev** [comment]
Yes! One question. Does git use different languages? If so then that grep
might not work.

**Comment by sebastienbarre** [comment]
Could be localized, you are correct. Option #2 then, because that would 
return an empty string if nothing is staged.

**Comment by jimthedev** [comment]
Ok, I'll make sure to write a test for this in what I currently calling v2. 

Side note: At the moment, I think v2 might actually be able to remain on the 1.x branch because as it is written, there should be no adapter breaking changes. The only thing that might make it called 2.x are some small cli changes. TBD.

**Comment by jimthedev** [comment]
Just a follow up for anyone who stumbles upon this thread in the future. If you want to capture output from diff to determine if there are staged files, you'll have to use `git diff --cached --exit-code` since by default cached mode runs in interactive mode. The `--exit-code` sends the results to stdout. Cheers.

**Comment by jimthedev** [comment]
One question I have on this @kentcdodds @sebastienbarre.  By adding this, I think we'll break the `git commit -A` functionality in the short term. Do people care? Is this acceptable? Everything I've been able to find recommends not using -A but I don't want to stream roll over it if people use it. I'll probably be able to insert some sort of conditional in the parser but want to get 2.0 out sooner rather than later so it might have to wait for 2.1.

**Comment by sebastienbarre** [comment]
You mean `git-cz -a -m` would break because nothing is staged? Can this check for whether files are staged or not only be done if `-a` was not passed as a parameter? Personally I'm partial to be able to use `git-cz -a -m`. Thanks. Just my 2 cents.

**Comment by jimthedev** [comment]
Cool. That's fair. I don't want to take away that functionality so I'll take a second look and try to get that working in the parser.

**Comment by kentcdodds** [comment]
I use `git commit -am 'message'` on a regular basis. But when I use
commitizen, I first `git add .` and then run `npm run commit` which runs an
npm script to run `git-cz` because I prefer to use the locally installed
binary. So it doesn't make much of a difference for me.

On Thu, Oct 15, 2015 at 11:41 AM Jim Cummins <notifications@github.com>
wrote:

> Cool. That's fair. I don't want to take away that functionality so I'll
> take a second look and try to get that working in the parser.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/commitizen/cz-cli/issues/7#issuecomment-148469042>.
>
-- 
- Kent C. Dodds <https://twitter.com/kentcdodds>

**Comment by jimthedev** [comment]
Excellent. Thanks for taking the time to describe your use cases.

**Comment by jimthedev** [comment]
Ok, I have improved it slightly. You can do `git-cz -a` (notice that -m is missing) which will add the files before going through the normal commitizen prompts process. The reason you can't add -m in is that since we're filling in the message for you based on your inputs, we show you an error because your input doesn't make sense. We can work on this more and I'll outline this as a known issue in the docs, but I just wanted to document why this choice was made somewhere.

**Comment by kentcdodds** [comment]
Looks like a perfect solution to me :+1:

On Thu, Oct 15, 2015 at 9:08 PM Jim Cummins <notifications@github.com>
wrote:

> Ok, I have improved it slightly. You can do git-cz -a (notice that -m is
> missing) which will add the files before going through the normal
> commitizen prompts process. The reason you can't add -m in is that since
> we're filling in the message for you based on your inputs, we show you an
> error because your input doesn't make sense. We can work on this more and
> I'll outline this as a known issue in the docs, but I just wanted to
> document why this choice was made somewhere.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/commitizen/cz-cli/issues/7#issuecomment-148586292>.
>
-- 
- Kent C. Dodds <https://twitter.com/kentcdodds>

**Comment by sebastienbarre** [comment]
Nice.
Minor. This worked for me:
```
$ ./node_modules/.bin/git-cz -a
```
This didn't:
```
$ npm run commit -- -a
> git-cz "-a"
```
where, in `package.json`:
```
  "scripts": {
    "commit": "git-cz",
```
This is minor of course. I could add `-a` in the script.

**Comment by jimthedev** [comment]
Ah, good to know. Reopening for now and will work on for 2.1.

**Comment by jimthedev** [comment]
I just tried this in 2.3.0 and `npm run commit -- -a` seemed to work for me. I'd made a few changes since the last time we spoke. Can you try again @sebastienbarre. I am on npm 2 and node 0.12.7.

**Comment by sebastienbarre** [comment]
@jimthedev I confirm it works for me as well. Thx.
