### ISSUE TITLE
Log githook output

### ISSUE THREAD

**Issue by kentcdodds** [commitizen/cz-cli#8]
I have a pre-commit hook that runs eslint. I don't see any output from eslint when that is running when using commitizen. Any idea why that is?

**Comment by kentcdodds** [comment]
Sorry, to be more specific, I see the output when the hook has finished and the commit has succeeded, but I don't see any of the output while it's in progress (like I do when I commit normally).

**Comment by jimthedev** [comment]
Hi Kent. Sorry it took me a bit to get back to you. Can you provide your pre-commit hook? In my case, I actually don't see any eslint output when I run `git cz` regardless of whether it succeeds or fails. Instead am greeted with a generic, relatively unhelpful error (✗ Commit failed. Did you forget to 'git add' your files?) or with a generic success message (✓ Commit succeeded). The only scenario that running git cz will output your eslint info right now is if you have not configured commitizen in package in the current working directory.  This is because by default, when commitizen is called but the current working directory repo does not have an adapter set in package.json/.czrc/.cz.js then it should completely remove itself from the scenario and revert to the normal git commit behavior.

Currently the 'user-friendly' :D default is that commitizen will try to commit, wait for the return code and then present a pretty message to the user based on the return code. This means that we're not piping the output of the command in real time. We probably could explore that scenario either by default or first behind a flag.

Again, if you have a scenario where you have a properly configured adapter in a repo and are getting actual eslint output back, I'd love to see it the pre-commit hook. Perhaps mine could be tweaked.

**Comment by kentcdodds** [comment]
Try out the angular-formly repo.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by kentcdodds** [comment]
Sorry, I misunderstood. I don't have a scenario where things are working
properly... Would love it though.

- Kent C. Dodds

(Sent from my mobile device, please forgive typos or brevity)

**Comment by jimthedev** [comment]
I am no longer using the pretty commit messages. Instead cz should output the raw git results. This *should* help with this although I'll probably have you double check it on release.

**Comment by kentcdodds** [comment]
:+1:

**Comment by jimthedev** [comment]
Ok, 2.0.2 seems to be the most stable release in the past 24 hours so we can probably check this with it. I can try it out but it might not be until tomomorrow.

**Comment by kentcdodds** [comment]
You'll notice that [it worked](https://github.com/formly-js/angular-formly/commit/d8dcf7c306914f5894976e084e5dfe4747864347) :-)

**Comment by kentcdodds** [comment]
Actually... Sorry.. No, I forgot what I was looking for. The word-wrap problems have been solved, but it's still not printing out the githook output until after the scripts are finished :-(

**Comment by jimthedev** [comment]
Alright. Thanks for checking. I'll dig in for 2.1.

**Comment by jimthedev** [comment]
I just put in a PR to gulp-git. Once that lands I'll be able to get incremental githook output working. Thanks for waiting. https://github.com/stevelacy/gulp-git/pull/99

**Comment by kentcdodds** [comment]
Sweet dude! :sunglasses:

**Comment by kentcdodds** [comment]
Finally got a chance to test this out. Works perfectly! Thanks!

**Comment by jimthedev** [comment]
Glad to hear. Thanks for testing!

**Comment by linxiaowu66** [comment]
@jimthedev  Hi,
I had read your posts, and I still can not know how can i output the ghooks log to stdout ?

Can you help me ?
