### ISSUE TITLE
Why are there no releases anymore?

### ISSUE THREAD

**Issue by chrisEff** [commitizen/cz-cli#897]
The latest released version is 4.2.4 from May of last year. A lot of changes have been merged to master after that, yet there hasn't been any new release ever since. Why is that?

This is especially problematic as 4.2.4 has some vulnerabilities.

**Comment by chrisEff** [comment]
I see that the project is using semantic-release and that multiple "fix" commits have been added since the last reelease. So they should definitely have triggered a new release, but didn't. Seems like there's something broken in the release proces...

**Comment by kdw2126** [comment]
It looks like the issue is that the release cycle used to be managed by Travis-CI.org and since that CI/CD tool was switched from this tool there are no releases.  I don't manage this repo so I don't have the ability to do this, but it seems like travis-CI.com is continuing to use the .travis.yml config that was [here](https://github.com/commitizen/cz-cli/pull/880/files).  Maybe a repo maintainer should sign up for that service so that releases can begin again?

**Comment by OmgImAlexis** [comment]
This can be closed as https://github.com/commitizen/cz-cli/pull/923 supersedes it.
